services:
  - type: web
    name: cartoon-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
    autoDeploy: true
